### ISSUE TITLE
Learn IDE issue.

### ISSUE THREAD

**Issue by carl1984r** [learn-co-curriculum/fewpjs-fns-as-first-class-data-do-behavior#10]
// ♥ learn open fewpjs-fns-as-first-class-data-do-behavior-online-web-sp-000
Looking for lesson...
Traceback (most recent call last):
        11: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
        10: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
         9: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-open:23:in `<main>'
         8: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-open:23:in `load'
         7: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/bin/learn-open:7:in `<to
p (required)>'
         6: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/opener.rb
:12:in `run'
         5: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/opener.rb
:38:in `run'
         4: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.r
b:19:in `classify'
         3: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.r
b:19:in `find'
         2: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.r
b:19:in `each'
         1: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.r
b:20:in `block in classify'
/usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons/ios_lesson.rb:6:in
 `detect': undefined method `any?' for false:FalseClass (NoMethodError)

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to the Learn platform.
[Raising issues on GitHub][issues] should be reserved for problems with the
curriculum itself (doesn't work, throws a Ruby error, etc.)

Our product team loves to hear about our Learners' innovative interface
improvements. You can reach them at support@learn.co. Alternatively, if Learn
is misbehaving, please direct your bug report to bugs@learn.co.

We'll pass this on and close this issue.

Thanks! :blue_heart:

**Comment by sgharms** [comment]
We have found the bug. It should work now.

**Comment by carl1984r** [comment]
Thx!
