### ISSUE TITLE
Receiving error message when opening in terminal + trying to submit 

### ISSUE THREAD

**Issue by Ricky199X** [learn-co-curriculum/fewpjs-fns-as-first-class-data-do-behavior#11]
Hi there,

I can't open this lab locally, I get this error message: 

**_gems/learn-open-1.2.28/lib/learn_open/lessons/ios_lesson.rb:6:in `detect': undefined method `any?' for false:FalseClass (NoMethodError)_**

To workaround it, I cloned from the repo and was able to get local tests to pass, but now when I try to run learn submit, I receive the following:

**_command': git '--git-dir=/Users/RickyRojas/fewpjs-fns-as-first-class-data-do-behavior-online-web-pt-041519/.git' '--work-tree=/Users/RickyRojas/fewpjs-fns-as-first-class-data-do-behavior-online-web-pt-041519' push 'origin' 'master'  2>&1:remote: Repository not found. (Git::GitExecuteError)
fatal: repository 'https://github.com/Ricky199X/fewpjs-fns-as-first-class-data-do-behavior-online-web-pt-041519.git/' not found_**

I'm receiving these same errors in Learn IDE as well, not just my local environment.

**Comment by sgharms** [comment]
We were missing a file used for running tests. We think it should be fixed now. Thanks.

If you create a file called `.learn` in the directory of this challenge  in your local environemnt:

```yaml
tags:
- lab
languages:
- JavaScript
```

things should work.

**Comment by sgharms** [comment]
I'm going to mark this as closed, please re-open if you're unable to get this working.
