### ISSUE TITLE
Shows message in greeting tag

### ISSUE THREAD

**Issue by Asilver-jpg** [learn-co-curriculum/fewpjs-fns-as-first-class-data-do-behavior#14]
My code shows the message in the greeting tag as requested yet does not pass the tests. The content grabbed by the text is undefined.

**Comment by ivalentine** [comment]
I have worked with two students today who are having the same issue:
@Pwako11
@Yumacorn

Fetching the element in the JS console in the browser works, but the same code does not work when running the tests.

**Comment by ihollander** [comment]
Fixed by https://github.com/learn-co-curriculum/fewpjs-fns-as-first-class-data-do-behavior/commit/346bdbdc32d9076b994cc351948144d64d4f2445
