### ISSUE TITLE
Test issues

### ISSUE THREAD

**Issue by timothylevi** [learn-co-curriculum/fewpjs-fns-as-first-class-data-do-behavior#6]
* Tests are different between master and solution branches
* Unclear whether to send number or string as argument to greet
* Isn't testing that this line of code runs from solution `document.getElementById("greeting").innerHTML = greet;` and it may not be clear from README that students need to put that text into the H1

**Comment by sgharms** [comment]
@timothylevi I think all of these are corrected now.
