### ISSUE TITLE
Misleading readme

### ISSUE THREAD

**Issue by PeteHanner** [learn-co-curriculum/fewpjs-fns-as-first-class-data-do-behavior#9]
The note under `displayMessage()` is misleading - it makes it sound as though the method is supposed to display the time in h1, when actually it's supposed to replace the inner text of h1 with the provided argument. It's possible this note was meant to be under the `greet()` section? It makes more sense there and would help with the solution of implementing that function.

**Comment by sgharms** [comment]
I agree with your assessment. The note will be moved up one bloc.
